server:
  port: 8000

mysql:
  username: root
  password: 123456789
  url: tcp(localhost:3306)/mall?charset=utf8&parseTime=True&loc=Local

upload:
  savePath: /tmp/resource/images/
  accessUrl: http://localhost:8000/image/

jwt:
  signingKey: z3d6k8v0n3w7m9sa1fd0u09h