server:
  port: 8000
  release_mode: true

mysql:
  username: root
  password: 123456789
  # Used in Docker
  url: tcp(mysql:3306)/mall?charset=utf8&parseTime=True&loc=Local
  # url: tcp(localhost:3306)/mall?charset=utf8&parseTime=True&loc=Local

redis:
  addr: redis:6379
  # addr: localhost:6379

upload:
  savePath: /tmp/resource/images/
  accessUrl: http://localhost:8000/image/

jwt:
  signingKey: z3d6k8v0n3w7m9sa1fd0u09h
